<?php

//-----------------------------------------------------------------------------
//	Add or update Sales Invoice
//
function get_tax_group_id($debtor_no)
{
    $sql = "SELECT tax_group_id FROM ".TB_PREF."cust_branch 
	WHERE debtor_no = ".db_escape($debtor_no)
	
	;
    $result = db_query($sql, "could not retreive default customer currency code");
    $row = db_fetch_row($result);
    return $row['0'];
}
function write_sales_invoice(&$invoice)
{
	global $Refs, $db_connections;

	$trans_no = $invoice->trans_no;
	if (is_array($trans_no))
		$trans_no = key($trans_no);

	$date_ = $invoice->document_date;
	$charge_shipping =$invoice->freight_cost;

	begin_transaction();
    $tax_group_id = get_tax_group_id($invoice->customer_id);

	hook_db_prewrite($invoice, ST_SALESINVOICE);
	$company_data = get_company_prefs();

//	S.H
	$GetShipper = get_shipper_for_invoice($invoice->ship_via);

	$branch_data = get_branch_accounts($invoice->Branch);

	$customer = get_customer($invoice->customer_id);

	add_new_exchange_rate($customer['curr_code'], $date_, $invoice->ex_rate);

	// offer price values without freight costs
	$items_total = $invoice->get_items_total_dispatch();
	$freight_tax = $invoice->get_shipping_tax();

	if (!$invoice->is_prepaid())
		update_customer_trans_version(get_parent_type(ST_SALESINVOICE), $invoice->src_docs);
    elseif (count($invoice->prepayments)) {	// partial invoice //ansar 26-08-17
        $last_payment = end($invoice->prepayments);
        $gl_date = sql2date($last_payment['tran_date']);
    } else {	// final invoice
        $gl_date = $invoice->document_date;
    }
	$ov_gst = 0;
	$taxes = $invoice->get_taxes(); // all taxes with freight_tax
	$dec = user_price_dec();
	foreach ($taxes as $taxitem) {
		$taxitem['Value'] =  round2($taxitem['Value'], $dec);
		$ov_gst +=  $taxitem['Value'];
	}

	if($invoice->tax_included==0) {
	    $items_added_tax = $ov_gst-$freight_tax;
	    $freight_added_tax = $freight_tax;
	} else {
	    $items_added_tax = 0;
	    $freight_added_tax = 0;
	}

	/* Insert/update the debtor_trans */
	$sales_order = $invoice->order_no;
	if (is_array($sales_order))
			$sales_order = $sales_order[0]; // assume all crucial SO data are same for every delivery

	if ($trans_no) {
        $allocs = get_payments_for($trans_no, ST_SALESINVOICE, $invoice->customer_id);//ansar 26-08-17
		//$allocs = get_payments_for($trans_no, ST_SALESINVOICE);
		delete_comments(ST_SALESINVOICE, $trans_no);
		void_gl_trans(ST_SALESINVOICE, $trans_no, true);
		void_trans_tax_details(ST_SALESINVOICE, $trans_no);
	} else
        $allocs = get_payments_for($invoice->order_no, ST_SALESORDER, $invoice->customer_id);//ansar 26-08-17
		//$allocs = get_payments_for($invoice->order_no, ST_SALESORDER);

	if ($invoice->is_prepaid()) // selected prepayment is already in cart
	{
		$allocs = $invoice->prepayments;
		// values posted are reduced by prepaid_factor
		$prepaid_factor = $invoice->prep_amount/$invoice->get_trans_total();
	} else {
		$prepaid_factor = 1;
	}

	 // write_customer_trans have to be called after optional void_cust_allocations above
	$invoice_no = write_customer_trans(ST_SALESINVOICE, $trans_no, $invoice->customer_id,
		$invoice->Branch, $invoice->document_date, $invoice->reference, $items_total, 0,
		$items_added_tax, $invoice->freight_cost, $freight_added_tax,
		$invoice->sales_type, $sales_order, $invoice->ship_via, 
		$invoice->due_date, 0, 0, $invoice->dimension_id, 
		$invoice->dimension2_id, $invoice->payment, $invoice->tax_included, $invoice->prep_amount,
		0,0,0,0,0,0,0,0,0,0,$invoice->discount1, $invoice->discount2,$invoice->cheque_date,0,$invoice->text1,0,0,$invoice->salesman,$invoice->h_amount1,"",$invoice->cust_ref,$tax_group_id);
		
   
    //SMS Configure for DMNWS (S.H.G)
    if($db_connections[$_SESSION["wa_current_user"]->company]["name"] == 'DMNWS')
    {
        $path_to_root = "..";
        include_once($path_to_root . "/includes/ui/sms_send.inc");
        $outstanding = get_customer_details_balance_sms($invoice->customer_id, $invoice->customer_id);
        $balance = $outstanding["Balance"];
        $original = array('amount', 'outstanding');
        $replaced = array($items_total, $balance);
        $GetTemplate = get_select_template_sms(ST_SALESINVOICE);
        $Message = $GetTemplate['template'];
        $sentence = str_replace($original, $replaced, $Message);
        $sql = "SELECT * FROM `0_crm_persons` WHERE `id` IN (
            SELECT person_id FROM `0_crm_contacts` WHERE `type`='cust_branch' AND `action`='general' AND entity_id IN (
            SELECT branch_code FROM `0_cust_branch` WHERE debtor_no=".db_escape($invoice->customer_id).") );";
        $query = db_query($sql, "Error");
        $fetch = db_fetch($query);
        if($company_data['auto_send_sms'] == 1) // enable from Company Setup
            sms_send($fetch['phone'], htmlspecialchars_decode($sentence));
    }
//========================================================================


	if ($trans_no == 0) {
		$invoice->trans_no = array($invoice_no=>0);
	} else
		move_trans_attachments(ST_SALESINVOICE, $trans_no, $invoice_no);

	$total = 0;
	// for prepayments use deferred income account if set
	$sales_account = $invoice->is_prepaid() ? get_company_pref('deferred_income_act') : 0;

	foreach ($invoice->line_items as $line_no => $invoice_line) {
		$qty_dispatched="";
		$item=get_item($invoice_line->stock_id);
		if($invoice_line->units_id !=  $item['units'])
		{
			if($item['con_type'] == 0)
			{
				$qty_dispatched =$invoice_line->qty_dispatched /$invoice_line->con_factor;
			}
			else
			{
				$qty_dispatched =$invoice_line->con_factor / $invoice_line->qty_dispatched ;
			}
		}
		else
		{
			$qty_dispatched =$invoice_line->qty_dispatched;
		}
	//	$qty = $qty_dispatched;
		
		
			$qty = $invoice_line->qty_dispatched;
		
		$line_taxfree_price = get_tax_free_price_for_item($invoice_line->stock_id,
			$invoice_line->price * $qty, 0, $invoice->tax_included,
			$invoice->tax_group_array);

		$line_tax = get_full_price_for_item($invoice_line->stock_id,
			$invoice_line->price * $qty, 0, $invoice->tax_included,
			$invoice->tax_group_array) - $line_taxfree_price;


		write_customer_trans_detail_item(ST_SALESINVOICE, $invoice_no, $invoice_line->stock_id,
			$invoice_line->item_description, $qty_dispatched,
			$invoice_line->line_price(), $qty ? $line_tax/$qty : 0, $invoice_line->discount_percent,
			$invoice_line->standard_cost, $invoice_line->src_id,
			$trans_no ? $invoice_line->id : 0,$invoice_line->units_id,$invoice_line->con_factor,
			$invoice_line->text1,$invoice_line->text2,
			$invoice_line->text3,$invoice_line->text4,$invoice_line->text5,$invoice_line->text6,
			$invoice_line->amount1,$invoice_line->amount2,
			$invoice_line->amount3,$invoice_line->amount4,$invoice_line->amount5,$invoice_line->amount6,
			$invoice_line->date1,$invoice_line->date2,
			$invoice_line->date3,
			$invoice_line->combo1,$invoice_line->combo2,
			$invoice_line->combo3,$invoice_line->combo4,$invoice_line->combo5,
			$invoice_line->combo6,$invoice_line->batch,$invoice_line->item_location,
            $invoice_line->text7,$invoice_line->bonus);

		// Update delivery items for the quantity invoiced
		if ($invoice_line->qty_old != $qty_dispatched)
		{
			if ($invoice->is_prepaid())
				update_prepaid_so_line($invoice_line->src_id, $qty_dispatched-$invoice_line->qty_old);
			else
				update_parent_line(ST_SALESINVOICE, $invoice_line->src_id, ($qty_dispatched-$invoice_line->qty_old));
		}
		
		$GetCode = get_salesman($invoice->salesman);
		
		if ($qty_dispatched != 0) {
			$stock_gl_code = get_stock_gl_code($invoice_line->stock_id);

			if ($invoice_line->line_price() != 0) {
				//Post sales transaction to GL credit sales

				// If there is a Branch Sales Account, then override with this,
				// else take the Item Sales Account
				if (!$invoice->is_prepaid())
					$sales_account = ($branch_data['sales_account'] != "" ? $branch_data['sales_account'] : $stock_gl_code['sales_account']);
				// If there is a Customer Dimension, then override with this,
				// else take the Item Dimension (if any)
				$dim = ($invoice->dimension_id != $customer['dimension_id'] ? $invoice->dimension_id : 
					($customer['dimension_id'] != 0 ? $customer["dimension_id"] : $stock_gl_code["dimension_id"]));
				$dim2 = ($invoice->dimension2_id != $customer['dimension2_id'] ? $invoice->dimension2_id : 
					($customer['dimension2_id'] != 0 ? $customer["dimension2_id"] : $stock_gl_code["dimension2_id"]));
					
					
						$Total_ = $line_taxfree_price*$prepaid_factor;
				$TotalInvoice = $Total_ - $invoice->h_amount1;
					
			//	$total += add_gl_trans_customer(ST_SALESINVOICE, $invoice_no, //$date_, $sales_account, $dim, $dim2,
			//		-$line_taxfree_price*$prepaid_factor,
				//	$invoice->customer_id, "The sales price GL posting could not //be inserted");

			$total += add_gl_trans_customer(ST_SALESINVOICE, $invoice_no, $date_, $sales_account, $dim, $dim2,
					-$TotalInvoice,
					$invoice->customer_id, "The sales price GL posting could not be inserted");
				if ($invoice->h_amount1 != 0)
				{
					$total += add_gl_trans_customer(ST_SALESINVOICE, $invoice_no, $date_,
						$GetCode["gl_account"], $dim, $dim2,/// 
						(-$invoice->h_amount1),
						$invoice->customer_id, "The sales discount GL posting could not be inserted");
				} /*end of $invoice->h_amount1 != 0 */
			
			
			
				if ($invoice_line->discount_percent != 0)
				{
					$total += add_gl_trans_customer(ST_SALESINVOICE, $invoice_no, $date_,
						$branch_data["sales_discount_account"], $dim, $dim2,
						($line_taxfree_price * $invoice_line->discount_percent)*$prepaid_factor,
						$invoice->customer_id, "The sales discount GL posting could not be inserted");
				} /*end of if discount !=0 */
			}
		} /*quantity dispatched is more than 0 */
	} /*end of delivery_line loop */
	$TotalDiscount = $invoice->discount1 + $invoice->discount2;

	if (($items_total + $charge_shipping) != 0) {
		$total += add_gl_trans_customer(ST_SALESINVOICE, $invoice_no, $date_, $branch_data["receivables_account"], 0, 0,
			($items_total + $charge_shipping + $items_added_tax + $freight_added_tax - $TotalDiscount)*$prepaid_factor,
			$invoice->customer_id, "The total debtor GL posting could not be inserted");
	}
	if ($invoice->discount1 != 0)
	{
		$total += add_gl_trans_customer(ST_SALESINVOICE, $invoice_no, $date_,
			get_company_pref('discount1'), $dim, $dim2,
			$invoice->discount1,
			$invoice->customer_id, "The sales discount GL posting could not be inserted");
	}
	if ($invoice->discount2 != 0)
	{
		$total += add_gl_trans_customer(ST_SALESINVOICE, $invoice_no, $date_,
			get_company_pref('discount2'), $dim, $dim2,
			$invoice->discount2,
			$invoice->customer_id, "The sales discount GL posting could not be inserted");
	}
	$to_allocate = ($items_total + $charge_shipping + $items_added_tax + $freight_added_tax);

	if ($charge_shipping != 0) {
	    
	    global  $db_connections;
	if($db_connections[$_SESSION["wa_current_user"]->company]["name"] == 'HOC' ){
		$total += add_gl_trans_customer(ST_SALESINVOICE, $invoice_no, $date_, /*$company_data["freight_act"]*/$GetShipper['shipping_account'], $dim, $dim2,
			-$invoice->get_tax_free_shipping()*$prepaid_factor, $invoice->customer_id,
			"The freight GL posting could not be inserted");
	}
	else{
	$total += add_gl_trans_customer(ST_SALESINVOICE, $invoice_no, $date_, $company_data["freight_act"]/*$GetShipper['shipping_account']*/, $dim, $dim2,
			-$invoice->get_tax_free_shipping()*$prepaid_factor, $invoice->customer_id,
			"The freight GL posting could not be inserted");
	}
	}
	// post all taxes
	foreach ($taxes as $taxitem) {
		if ($taxitem['Net'] != 0) {
			$ex_rate = get_exchange_rate_from_home_currency(get_customer_currency($invoice->customer_id), $date_);
			add_trans_tax_details(ST_SALESINVOICE, $invoice_no, $taxitem['tax_type_id'],
				$taxitem['rate'], $invoice->tax_included, $prepaid_factor*$taxitem['Value'],
				 $taxitem['Net'], $ex_rate, $date_, $invoice->reference, TR_OUTPUT);
			if (isset($taxitem['sales_gl_code']))
				$total += add_gl_trans_customer(ST_SALESINVOICE, $invoice_no, $date_, $taxitem['sales_gl_code'], 0, 0,
					(-$taxitem['Value'])*$prepaid_factor, $invoice->customer_id,
					"A tax GL posting could not be inserted");
		}
	}

	/*Post a balance post if $total != 0 */
	add_gl_balance(ST_SALESINVOICE, $invoice_no, $date_, -$total, PT_CUSTOMER, $invoice->customer_id);	

	add_comments(ST_SALESINVOICE, $invoice_no, $date_, $invoice->Comments);

	if ($trans_no == 0) {
		$Refs->save(ST_SALESINVOICE, $invoice_no, $invoice->reference, null, $invoice->fixed_asset); 
		if ($invoice->payment_terms['cash_sale'] && $invoice->ToBankAccount
		/*$invoice->pos['pos_account']*/ ) {
		$discount = $invoice->discount1 + $invoice->discount2;
			$amount = $items_total + $items_added_tax + $invoice->freight_cost 
				+ $freight_added_tax - $discount;

			// to use debtors.pmt_discount on cash sale:
			// extend invoice entry page with final amount after discount 
			// and change line below.

		///	$discount = 0; // $invoice->cash_discount*$amount;
		
			
			$pmtno = write_customer_payment(0, $invoice->customer_id, 
				$invoice->Branch, $invoice->ToBankAccount , $date_,
                $Refs->get_next(ST_CUSTPAYMENT, null, array('customer' => $invoice->customer_id,
                    'branch' => $invoice->Branch, 'date' => $date_)),
                $amount, $discount,
                _('Cash invoice').' '.$invoice_no);
			add_cust_allocation($amount, ST_CUSTPAYMENT, $pmtno, ST_SALESINVOICE, $invoice_no, $invoice->customer_id, $date_);

			update_debtor_trans_allocation(ST_SALESINVOICE, $invoice_no, $invoice->customer_id);
			update_debtor_trans_allocation(ST_CUSTPAYMENT, $pmtno, $invoice->customer_id);
		}
	}
	//reallocate_payments($invoice_no, ST_SALESINVOICE, $date_, $to_allocate, $allocs);//ansar 26-08-17
    reallocate_payments($invoice_no, ST_SALESINVOICE, $date_, $to_allocate, $allocs, $invoice->customer_id);
	hook_db_postwrite($invoice, ST_SALESINVOICE);

	commit_transaction();

	return $invoice_no;
}

//--------------------------------------------------------------------------------------------------

function void_sales_invoice($type, $type_no)
{
	begin_transaction();

	hook_db_prevoid($type, $type_no);
	void_bank_trans($type, $type_no, true);
	void_gl_trans($type, $type_no, true);

	// reverse all the changes in parent document(s)
	$factor = get_cust_prepayment_invoice_factor($type_no);
	if ($factor != 0)
	{
		$lines = get_customer_trans_details($type, $type_no);
		while($line = db_fetch($lines))
		{
			update_prepaid_so_line($line['src_id'], -$factor*$line['quantity']);
		}
	}
	else
	{
		$deliveries = get_sales_parent_numbers($type, $type_no);

		if ($deliveries !== 0) {
			if ($type == ST_SALESINVOICE && count($deliveries) == 1 && get_reference(ST_CUSTDELIVERY, $deliveries[0]) == "auto")
			{
				void_sales_delivery(ST_CUSTDELIVERY, $deliveries[0], false);
				$date_ = Today();
				add_audit_trail(ST_CUSTDELIVERY, $deliveries[0], $date_, _("Voided."));
				add_voided_entry(ST_CUSTDELIVERY, $deliveries[0], $date_, "");
			}
			else
			{
				$srcdetails = get_sales_parent_lines($type, $type_no);
				while ($row = db_fetch($srcdetails)) {
					update_parent_line($type, $row['id'], -$row['quantity']);
				}
			}
		}
	}
	// clear details after they've been reversed in the sales order
	void_customer_trans_details($type, $type_no);

	void_stock_move($type, $type_no); // in case of credit note with return

	void_trans_tax_details($type, $type_no);

	void_cust_allocations($type, $type_no);

	// do this last because other voidings can depend on it - especially voiding
	// DO NOT MOVE THIS ABOVE VOIDING or we can end up with trans with alloc < 0
	void_customer_trans($type, $type_no);

	commit_transaction();
}

function is_cust_invoice_credited($trans_no)
{
	return db_num_rows(get_sales_child_lines(ST_SALESINVOICE, $trans_no));
}

function get_cust_prepayment_invoice_factor($trans_no)
{
	$sql = "SELECT IF(dt.prep_amount>0, dt.prep_amount/so.total ,0) 
		FROM ".TB_PREF."debtor_trans dt
		LEFT JOIN ".TB_PREF."sales_orders so ON so.trans_type=".ST_SALESORDER." AND so.order_no=dt.order_
		 WHERE dt.type=".ST_SALESINVOICE." AND trans_no=".db_escape($trans_no);
	$row = db_fetch(db_query($sql, 'cannot retrieve prepaid invoice factor'));
	return $row[0];
}
//ansar 26-08-17
function prepaid_invoice_remainder($order)
{
    $sql = "SELECT so.total - IFNULL(SUM(inv.prep_amount),0) FROM "
        .TB_PREF."sales_orders so,
		".TB_PREF."debtor_trans inv,
		".TB_PREF."payment_terms pt
		WHERE  so.order_no=".db_escape($order)
        ." AND so.trans_type=".ST_SALESORDER
        ." AND inv.type=".ST_SALESINVOICE
        ." AND inv.order_=so.order_no"
        ." AND so.payment_terms=pt.terms_indicator"
        ." AND inv.payment_terms=pt.terms_indicator"
        ." AND pt.days_before_due = -1";

    $result = db_fetch(db_query($sql, "cannot find final invoice value"));
    return $result[0] ? $result[0] : 0;
}

/*
	Find oldest delivery date for sales invoice
*/
function get_oldest_delivery_date($invoice_no)
{
	$sql = "SELECT MIN(trans.tran_date)
			FROM
				".TB_PREF."debtor_trans_details del
			LEFT JOIN ".TB_PREF."debtor_trans_details inv
				ON inv.src_id=del.id
			LEFT JOIN ".TB_PREF."debtor_trans trans 
				ON trans.type=".ST_CUSTDELIVERY." AND trans.trans_no = del.debtor_trans_no
			WHERE
				inv.debtor_trans_type=".ST_SALESINVOICE
				." AND inv.debtor_trans_no=".db_escape($invoice_no);
	$res = db_query($sql, 'cannot find oldest delivery date');
	$date = db_fetch($res);
	return $date[0];
}

/*
	Find oldest payment date for sales invoice
*/
function get_oldest_payment_date($invoice_no)
{
	$sql = "SELECT MIN(payment.tran_date)
			FROM
			".TB_PREF."cust_allocations alloc,
			".TB_PREF."debtor_trans payment
			WHERE
				alloc.trans_type_to=".ST_SALESINVOICE." AND alloc.trans_no_to=".db_escape($invoice_no)
			." AND alloc.trans_type_from=payment.type AND alloc.trans_no_from=payment.trans_no";
	$res = db_query($sql, 'cannot find oldest delivery date');
	$date = db_fetch($res);
	return $date[0];
}
