<?php
/*
include_once($path_to_root . "/includes/Mobile_Detect.php");

// Make sure the auto select box for searching not causing trouble.
if ($auto_select_box == true) {
	// Disable auto select box on mobile device because it has problem
	// with the soft keyboard input.
	$detect = new Mobile_Detect();
	if ($detect->isMobile()) {
		$auto_select_box = false;
	}

	// Disable auto select box when the search feature for item, supplier,
	// or customer is turned on.
	if (get_company_pref('no_item_list') !=0 ||
			get_company_pref('no_customer_list') != 0 ||
			get_company_pref('no_supplier_list') != 0) {
		$auto_select_box = false;
	}
}
*/
